# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(991, 687)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.box_input_file = QtWidgets.QComboBox(self.groupBox)
        self.box_input_file.setObjectName("box_input_file")
        self.gridLayout_3.addWidget(self.box_input_file, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 1)
        self.box_input_type = QtWidgets.QComboBox(self.groupBox)
        self.box_input_type.setObjectName("box_input_type")
        self.box_input_type.addItem("")
        self.gridLayout_3.addWidget(self.box_input_type, 1, 1, 1, 1)
        self.show_input = QtWidgets.QPushButton(self.groupBox)
        self.show_input.setObjectName("show_input")
        self.gridLayout_3.addWidget(self.show_input, 2, 0, 1, 2)
        self.gridLayout_6.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.Ttip = QtWidgets.QLineEdit(self.groupBox_2)
        self.Ttip.setObjectName("Ttip")
        self.gridLayout.addWidget(self.Ttip, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.Tsur = QtWidgets.QLineEdit(self.groupBox_2)
        self.Tsur.setObjectName("Tsur")
        self.gridLayout.addWidget(self.Tsur, 2, 1, 1, 1)
        self.box_Ttip = QtWidgets.QComboBox(self.groupBox_2)
        self.box_Ttip.setObjectName("box_Ttip")
        self.gridLayout.addWidget(self.box_Ttip, 1, 2, 1, 1)
        self.box_Tsur = QtWidgets.QComboBox(self.groupBox_2)
        self.box_Tsur.setObjectName("box_Tsur")
        self.gridLayout.addWidget(self.box_Tsur, 2, 2, 1, 1)
        self.delta = QtWidgets.QLineEdit(self.groupBox_2)
        self.delta.setObjectName("delta")
        self.gridLayout.addWidget(self.delta, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.box_delta = QtWidgets.QComboBox(self.groupBox_2)
        self.box_delta.setObjectName("box_delta")
        self.gridLayout.addWidget(self.box_delta, 3, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.gamma = QtWidgets.QLineEdit(self.groupBox_2)
        self.gamma.setObjectName("gamma")
        self.gridLayout.addWidget(self.gamma, 4, 1, 1, 1)
        self.box_gamma = QtWidgets.QComboBox(self.groupBox_2)
        self.box_gamma.setObjectName("box_gamma")
        self.gridLayout.addWidget(self.box_gamma, 4, 2, 1, 1)
        self.show_tip_dos = QtWidgets.QPushButton(self.groupBox_2)
        self.show_tip_dos.setObjectName("show_tip_dos")
        self.gridLayout.addWidget(self.show_tip_dos, 6, 0, 1, 3)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.ewindow = QtWidgets.QLineEdit(self.groupBox_2)
        self.ewindow.setObjectName("ewindow")
        self.gridLayout.addWidget(self.ewindow, 5, 1, 1, 1)
        self.box_ewindow = QtWidgets.QComboBox(self.groupBox_2)
        self.box_ewindow.setObjectName("box_ewindow")
        self.gridLayout.addWidget(self.box_ewindow, 5, 2, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.deconvolve = QtWidgets.QPushButton(self.groupBox_3)
        self.deconvolve.setObjectName("deconvolve")
        self.gridLayout_2.addWidget(self.deconvolve, 3, 0, 1, 2)
        self.box_mode = QtWidgets.QComboBox(self.groupBox_3)
        self.box_mode.setObjectName("box_mode")
        self.box_mode.addItem("")
        self.box_mode.addItem("")
        self.gridLayout_2.addWidget(self.box_mode, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.maxn = QtWidgets.QLineEdit(self.groupBox_3)
        self.maxn.setObjectName("maxn")
        self.gridLayout_2.addWidget(self.maxn, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.ntries = QtWidgets.QLineEdit(self.groupBox_3)
        self.ntries.setObjectName("ntries")
        self.gridLayout_2.addWidget(self.ntries, 1, 1, 1, 1)
        self.show_deconvolution = QtWidgets.QPushButton(self.groupBox_3)
        self.show_deconvolution.setObjectName("show_deconvolution")
        self.gridLayout_2.addWidget(self.show_deconvolution, 4, 0, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setEnabled(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.text_deconv_dos = QtWidgets.QTabWidget(self.groupBox_4)
        self.text_deconv_dos.setEnabled(True)
        self.text_deconv_dos.setObjectName("text_deconv_dos")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.text_input = QtWidgets.QTextEdit(self.tab)
        self.text_input.setObjectName("text_input")
        self.gridLayout_9.addWidget(self.text_input, 0, 0, 1, 1)
        self.text_deconv_dos.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.text_tip_dos = QtWidgets.QTextEdit(self.tab_2)
        self.text_tip_dos.setObjectName("text_tip_dos")
        self.gridLayout_8.addWidget(self.text_tip_dos, 0, 0, 1, 1)
        self.text_deconv_dos.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.text_dos = QtWidgets.QTextEdit(self.tab_3)
        self.text_dos.setObjectName("text_dos")
        self.gridLayout_7.addWidget(self.text_dos, 0, 0, 1, 1)
        self.text_deconv_dos.addTab(self.tab_3, "")
        self.gridLayout_11.addWidget(self.text_deconv_dos, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_4, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 991, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.text_deconv_dos.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "STMdeconvpy"))
        self.groupBox.setTitle(_translate("MainWindow", "Input and output"))
        self.label_7.setText(_translate("MainWindow", "Input file"))
        self.box_input_file.setToolTip(_translate("MainWindow", "Select the input file, this menu will list the *.cur files of the current directory"))
        self.label_10.setText(_translate("MainWindow", "Type of input"))
        self.box_input_type.setToolTip(_translate("MainWindow", "Tipe of input file, 1D for a one-dimensional dIdV curve"))
        self.box_input_type.setItemText(0, _translate("MainWindow", "1D"))
        self.show_input.setToolTip(_translate("MainWindow", "Show the input data"))
        self.show_input.setText(_translate("MainWindow", "Show input data"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Parameters"))
        self.Ttip.setToolTip(_translate("MainWindow", "Temperature of the tip"))
        self.Ttip.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "Tiip temperature"))
        self.label_2.setText(_translate("MainWindow", "Surface temperature"))
        self.Tsur.setToolTip(_translate("MainWindow", "Temperature of the surface"))
        self.Tsur.setText(_translate("MainWindow", "0"))
        self.delta.setToolTip(_translate("MainWindow", "Superconducting gap of the Tip"))
        self.delta.setText(_translate("MainWindow", "0"))
        self.label_3.setText(_translate("MainWindow", "Tip superconducting gap"))
        self.label_4.setText(_translate("MainWindow", "Tip gamma"))
        self.gamma.setToolTip(_translate("MainWindow", "Gamma of the Dynes superconductor assumed"))
        self.gamma.setText(_translate("MainWindow", "0"))
        self.show_tip_dos.setToolTip(_translate("MainWindow", "Show the DOS of the Tip at T=0"))
        self.show_tip_dos.setText(_translate("MainWindow", "Show Tip DOS"))
        self.label_11.setText(_translate("MainWindow", "Parameter"))
        self.label_12.setText(_translate("MainWindow", "Value"))
        self.label_13.setText(_translate("MainWindow", "Units"))
        self.label_8.setText(_translate("MainWindow", "Energy window"))
        self.ewindow.setText(_translate("MainWindow", "5"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Calculation"))
        self.deconvolve.setToolTip(_translate("MainWindow", "Perform the deconvolution and plot the result"))
        self.deconvolve.setText(_translate("MainWindow", "Deconvolve"))
        self.box_mode.setToolTip(_translate("MainWindow", "Select the calculation mode, \"Algebra\" is the fastest but it can be numerically unstable, \"Minimize\" allows to know the uncertainty of the deconvolution"))
        self.box_mode.setItemText(0, _translate("MainWindow", "Minimize"))
        self.box_mode.setItemText(1, _translate("MainWindow", "Algebra"))
        self.label_5.setText(_translate("MainWindow", "Calculation mode"))
        self.maxn.setToolTip(_translate("MainWindow", "Number of grid points used in the deconvolution, the more the better"))
        self.maxn.setText(_translate("MainWindow", "100"))
        self.label_6.setText(_translate("MainWindow", "Number of points"))
        self.label_9.setText(_translate("MainWindow", "Number of tries"))
        self.ntries.setToolTip(_translate("MainWindow", "Number of tries of the deconvolution, only used for the \"Minimize\" mode"))
        self.ntries.setText(_translate("MainWindow", "5"))
        self.show_deconvolution.setToolTip(_translate("MainWindow", "Plot the result of the deconvolution"))
        self.show_deconvolution.setText(_translate("MainWindow", "Show deconvolution"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Data"))
        self.text_deconv_dos.setToolTip(_translate("MainWindow", "Data files"))
        self.text_input.setToolTip(_translate("MainWindow", "Input data file"))
        self.text_deconv_dos.setTabText(self.text_deconv_dos.indexOf(self.tab), _translate("MainWindow", "Input data"))
        self.text_tip_dos.setToolTip(_translate("MainWindow", "DOS of the tip"))
        self.text_deconv_dos.setTabText(self.text_deconv_dos.indexOf(self.tab_2), _translate("MainWindow", "Tip DOS"))
        self.text_dos.setToolTip(_translate("MainWindow", "Deconvoluted DOS"))
        self.text_deconv_dos.setTabText(self.text_deconv_dos.indexOf(self.tab_3), _translate("MainWindow", "Deconvoluted DOS"))

